I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 2, in script
    define s = Character([sebastian_name])
  File "game/script.rpy", line 2, in <module>
    define s = Character([sebastian_name])
NameError: name 'sebastian_name' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 2, in script
    define s = Character([sebastian_name])
  File "/Users/jenniferwem/Misc/renpy-6.99.13-sdk/renpy/ast.py", line 1882, in execute
    value = renpy.python.py_eval_bytecode(self.code.bytecode)
  File "/Users/jenniferwem/Misc/renpy-6.99.13-sdk/renpy/python.py", line 1788, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 2, in <module>
    define s = Character([sebastian_name])
NameError: name 'sebastian_name' is not defined

Darwin-16.7.0-x86_64-i386-64bit
Ren'Py 6.99.13.2919
Concordia Jones 1.0
